on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings --cfg tokio_unstable
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
      - name: clippy
        run: cargo clippy --all-targets --all-features
      - name: rustfmt
        run: cargo fmt --check

  check-docs:
    name: Check docs
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings --cfg tokio_unstable --cfg docsrs
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-06-24
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
      - name: docs
        run: cargo doc --no-deps --all-features

  build-and-test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # 1.85 is the MSRV
        rust-version: ["1.85", "stable"]
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
      - uses: taiki-e/install-action@nextest
      - name: Build
        run: cargo build --all-features
      - name: Run tests
        run: cargo nextest run --all-features --no-tests pass
      - name: Doctests
        run: cargo test --all-features --doc
